// <auto-generated />
namespace LendADogDemo.Entities.DataContexts.LendADogMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MainMessRelationWithDog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MainMessRelationWithDog));
        
        string IMigrationMetadata.Id
        {
            get { return "201802070954142_MainMessRelationWithDog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
