// <auto-generated />
namespace LendADogDemo.Entities.DataContexts.LendADogMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixRequestMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixRequestMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101312339_Fix RequestMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
